# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o5NgYTYyJCtX3GXQf9C7pSJjQanzILDK
"""

!pip install ultralytics opencv-python -q

import cv2
import numpy as np
from ultralytics import YOLO
from google.colab.patches import cv2_imshow
from google.colab import files

print("Loading YOLOv8x model...")
model = YOLO('yolov8x.pt')
print("Model loaded successfully.\n")

# Upload Image
uploaded = files.upload()

if not uploaded:
    print("No image uploaded.")

else:

    img_path = next(iter(uploaded))
    img_original = cv2.imread(img_path)

    if img_original is None:
        print("Could not read image.")

    else:

        # Image Preprocessing
        def preprocess_image(img):

            lab = cv2.cvtColor(img, cv2.COLOR_BGR2LAB)

            l, a, b = cv2.split(lab)

            clahe = cv2.createCLAHE(
                clipLimit=2.0,
                tileGridSize=(8, 8)
            )

            l = clahe.apply(l)

            enhanced = cv2.merge([l, a, b])

            enhanced = cv2.cvtColor(
                enhanced,
                cv2.COLOR_LAB2BGR
            )

            denoised = cv2.fastNlMeansDenoisingColored(
                enhanced,
                None,
                5,
                5,
                7,
                21
            )

            return denoised

        print("Preprocessing image...")

        img_preprocessed = preprocess_image(img_original)

        img_display = img_original.copy()

        # Vehicle Classes
        VEHICLE_CLASSES = {
            2: 'Car',
            3: 'Motorcycle',
            5: 'Bus',
            7: 'Truck'
        }

        # Colors
        CLASS_COLORS = {
            'Car': (0, 255, 0),
            'Motorcycle': (0, 200, 255),
            'Bus': (255, 80, 0),
            'Truck': (0, 0, 255),
        }

        print("Running detection...")

        results = model.predict(
            source=img_preprocessed,
            conf=0.30,
            iou=0.40,
            imgsz=1280,
            augment=True,
            classes=list(VEHICLE_CLASSES.keys()),
            verbose=False
        )

        counts = {
            name: 0
            for name in VEHICLE_CLASSES.values()
        }

        detections = []

        # Store detections
        for r in results:

            for box in r.boxes:

                cls_id = int(box.cls.item())

                conf = float(box.conf.item())

                label = VEHICLE_CLASSES.get(cls_id)

                if label is None:
                    continue

                x1, y1, x2, y2 = map(
                    int,
                    box.xyxy[0].tolist()
                )

                detections.append(
                    (x1, y1, x2, y2, label, conf)
                )

        # IoU Function
        def compute_iou(boxA, boxB):

            xA = max(boxA[0], boxB[0])
            yA = max(boxA[1], boxB[1])
            xB = min(boxA[2], boxB[2])
            yB = min(boxA[3], boxB[3])

            inter = max(0, xB - xA) * max(0, yB - yA)

            if inter == 0:
                return 0.0

            areaA = (
                (boxA[2]-boxA[0]) *
                (boxA[3]-boxA[1])
            )

            areaB = (
                (boxB[2]-boxB[0]) *
                (boxB[3]-boxB[1])
            )

            return inter / float(
                areaA + areaB - inter
            )

        # Remove Duplicate Boxes
        def secondary_nms(detections, iou_thresh=0.50):

            detections = sorted(
                detections,
                key=lambda x: x[5],
                reverse=True
            )

            kept = []

            suppressed = set()

            for i, det_i in enumerate(detections):

                if i in suppressed:
                    continue

                kept.append(det_i)

                for j, det_j in enumerate(detections):

                    if j <= i or j in suppressed:
                        continue

                    if det_i[4] == det_j[4]:

                        iou = compute_iou(
                            det_i[:4],
                            det_j[:4]
                        )

                        if iou > iou_thresh:
                            suppressed.add(j)

            return kept

        clean_detections = secondary_nms(
            detections,
            iou_thresh=0.50
        )

        # Draw Boxes
        font = cv2.FONT_HERSHEY_DUPLEX

        for (
            x1,
            y1,
            x2,
            y2,
            label,
            conf
        ) in clean_detections:

            counts[label] += 1

            color = CLASS_COLORS[label]

            cv2.rectangle(
                img_display,
                (x1, y1),
                (x2, y2),
                color,
                3
            )

            text = f"{label} {conf:.2f}"

            (tw, th), _ = cv2.getTextSize(
                text,
                font,
                0.6,
                2
            )

            cv2.rectangle(
                img_display,
                (x1, y1 - th - 10),
                (x1 + tw + 6, y1),
                color,
                -1
            )

            cv2.putText(
                img_display,
                text,
                (x1 + 3, y1 - 5),
                font,
                0.6,
                (0, 0, 0),
                2
            )

        # Count Panel
        overlay = img_display.copy()

        panel_h = (
            30 +
            len([v for v in counts.values() if v > 0]) * 28 +
            40
        )

        cv2.rectangle(
            overlay,
            (10, 10),
            (270, 10 + panel_h),
            (0, 0, 0),
            -1
        )

        cv2.addWeighted(
            overlay,
            0.6,
            img_display,
            0.4,
            0,
            img_display
        )

        cv2.putText(
            img_display,
            "VEHICLE COUNT",
            (20, 35),
            font,
            0.7,
            (255, 255, 255),
            2
        )

        y_offset = 65

        for vehicle, count in counts.items():

            if count > 0:

                color = CLASS_COLORS[vehicle]

                cv2.putText(
                    img_display,
                    f"{vehicle:<12}: {count}",
                    (20, y_offset),
                    font,
                    0.6,
                    color,
                    1
                )

                y_offset += 28

        total = sum(counts.values())

        cv2.putText(
            img_display,
            f"TOTAL: {total}",
            (20, y_offset + 10),
            font,
            0.75,
            (255, 255, 255),
            2
        )

        # Console Output
        print("\nVehicle Detection Report\n")

        for vehicle, count in counts.items():

            if count > 0:
                print(f"{vehicle}: {count}")

        print(f"\nTotal Vehicles: {total}")

        print("\nModel: YOLOv8x")
        print("Image Size: 1280")
        print("Augmentation: Enabled")

        # Show Output
        cv2_imshow(img_display)